const std = @import("std");
const builtin = @import("builtin");

pub const config_rel_path = ".config/ugrant/config.toml";
pub const state_rel_dir = ".local/state/ugrant";
pub const db_filename = "state.db";
pub const keys_filename = "keys.json";
pub const default_config =
    \\# ugrant configuration
    \\# Generated by `ugrant init`
    \\
    \\[storage]
    \\refresh_skew_seconds = 300
    \\lease_timeout_seconds = 30
    \\poll_interval_ms = 250
    \\max_wait_seconds = 60
    \\
;

pub const StorageConfig = struct {
    refresh_skew_seconds: i64 = 300,
    lease_timeout_seconds: i64 = 30,
    poll_interval_ms: u64 = 250,
    max_wait_seconds: i64 = 60,
};

pub const Paths = struct {
    config_path: []const u8,
    state_dir: []const u8,
    db_path: []const u8,
    keys_path: []const u8,

    pub fn deinit(self: Paths, allocator: std.mem.Allocator) void {
        allocator.free(self.config_path);
        allocator.free(self.state_dir);
        allocator.free(self.db_path);
        allocator.free(self.keys_path);
    }
};

pub fn resolvePaths(allocator: std.mem.Allocator) !Paths {
    const home = std.posix.getenv("HOME") orelse return error.MissingHome;
    const config_path = try std.fs.path.join(allocator, &.{ home, config_rel_path });
    const state_dir = try std.fs.path.join(allocator, &.{ home, state_rel_dir });
    const db_path = try std.fs.path.join(allocator, &.{ state_dir, db_filename });
    const keys_path = try std.fs.path.join(allocator, &.{ state_dir, keys_filename });
    return .{ .config_path = config_path, .state_dir = state_dir, .db_path = db_path, .keys_path = keys_path };
}

pub fn ensureParentDirs(paths: Paths) !void {
    try std.fs.cwd().makePath(paths.state_dir);
    if (std.fs.path.dirname(paths.config_path)) |config_dir| try std.fs.cwd().makePath(config_dir);
}

pub fn ensureConfig(config_path: []const u8) !void {
    if (!(try fileExists(config_path))) {
        var file = try std.fs.createFileAbsolute(config_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll(default_config);
    }
}

pub fn requireInitialized(paths: Paths) !void {
    if (!(try fileExists(paths.keys_path)) or !(try fileExists(paths.db_path))) return error.NotInitialized;
}

pub fn fileExists(path: []const u8) !bool {
    std.fs.accessAbsolute(path, .{}) catch |e| switch (e) {
        error.FileNotFound => return false,
        else => return e,
    };
    return true;
}

pub fn nowTs() i64 {
    return std.time.timestamp();
}

pub fn loadStorageConfig(allocator: std.mem.Allocator, config_path: []const u8) !StorageConfig {
    var cfg = StorageConfig{};
    const bytes = std.fs.cwd().readFileAlloc(allocator, config_path, 64 * 1024) catch |err| switch (err) {
        error.FileNotFound => return cfg,
        else => return err,
    };
    defer allocator.free(bytes);

    var in_storage = false;
    var lines = std.mem.splitScalar(u8, bytes, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \r\t");
        if (line.len == 0 or line[0] == '#') continue;
        if (line[0] == '[' and line[line.len - 1] == ']') {
            in_storage = std.mem.eql(u8, std.mem.trim(u8, line[1 .. line.len - 1], " \t"), "storage");
            continue;
        }
        if (!in_storage) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const key = std.mem.trim(u8, line[0..eq], " \t");
        const value = std.mem.trim(u8, line[eq + 1 ..], " \t");
        if (std.mem.eql(u8, key, "refresh_skew_seconds")) cfg.refresh_skew_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "lease_timeout_seconds")) cfg.lease_timeout_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "poll_interval_ms")) cfg.poll_interval_ms = try std.fmt.parseInt(u64, value, 10) else if (std.mem.eql(u8, key, "max_wait_seconds")) cfg.max_wait_seconds = try std.fmt.parseInt(i64, value, 10);
    }
    return cfg;
}

pub fn envTruthy(name: []const u8) bool {
    const raw = std.posix.getenv(name) orelse return false;
    return std.mem.eql(u8, raw, "1") or std.ascii.eqlIgnoreCase(raw, "true") or std.ascii.eqlIgnoreCase(raw, "yes");
}

pub fn commandExists(allocator: std.mem.Allocator, name: []const u8) bool {
    const result = std.process.Child.run(.{ .allocator = allocator, .argv = &.{ "sh", "-c", "command -v \"$1\" >/dev/null 2>&1", "sh", name }, .max_output_bytes = 0 }) catch return false;
    return switch (result.term) {
        .Exited => |code| code == 0,
        else => false,
    };
}

pub fn backendAvailable(allocator: std.mem.Allocator, backend: []const u8) bool {
    if (std.mem.eql(u8, backend, "tpm2")) {
        if (envTruthy("UGRANT_TEST_TPM2_AVAILABLE")) return true;
        return commandExists(allocator, "tpm2_create") and commandExists(allocator, "tpm2_unseal") and commandExists(allocator, "tpm2_createprimary") and commandExists(allocator, "tpm2_load");
    }
    if (std.mem.eql(u8, backend, "platform-secure-store")) {
        if (envTruthy("UGRANT_TEST_PLATFORM_STORE_AVAILABLE")) return true;
        return commandExists(allocator, "secret-tool") and std.posix.getenv("DBUS_SESSION_BUS_ADDRESS") != null;
    }
    if (std.mem.eql(u8, backend, "passphrase")) return true;
    if (std.mem.eql(u8, backend, "insecure-keyfile")) return true;
    return false;
}

pub fn resolvePlatformSecureStoreBackend(tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (builtin.os.tag == .linux and tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return error.WrapBackendUnavailable;
}

pub fn resolveBackendChoice(requested_backend: ?[]const u8, allow_insecure: bool, tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (requested_backend) |backend| {
        if (std.mem.eql(u8, backend, "insecure-keyfile")) {
            if (!allow_insecure) return error.InsecureBackendRequiresOptIn;
            return "insecure-keyfile";
        }
        if (std.mem.eql(u8, backend, "platform-secure-store")) return resolvePlatformSecureStoreBackend(tpm2_available, platform_store_available);
        if (std.mem.eql(u8, backend, "tpm2")) {
            if (!tpm2_available) return error.WrapBackendUnavailable;
            return "tpm2";
        }
        if (std.mem.eql(u8, backend, "passphrase")) return "passphrase";
        return error.WrapBackendUnavailable;
    }

    if (tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return "passphrase";
}

pub fn chooseInitBackend(allocator: std.mem.Allocator, requested_backend: ?[]const u8, allow_insecure: bool) ![]const u8 {
    return resolveBackendChoice(requested_backend, allow_insecure, backendAvailable(allocator, "tpm2"), backendAvailable(allocator, "platform-secure-store"));
}

test "choose init backend respects explicit backend and insecure opt-in" {
    const backend = try chooseInitBackend(std.testing.allocator, "passphrase", false);
    try std.testing.expectEqualStrings("passphrase", backend);
    try std.testing.expectError(error.InsecureBackendRequiresOptIn, chooseInitBackend(std.testing.allocator, "insecure-keyfile", false));
}

test "platform-secure-store resolves to strongest Linux backend" {
    if (builtin.os.tag != .linux) return;

    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice("platform-secure-store", false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice("platform-secure-store", false, false, true));
    try std.testing.expectError(error.WrapBackendUnavailable, resolveBackendChoice("platform-secure-store", false, false, false));
}

test "default backend selection still prefers strongest available backend" {
    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice(null, false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice(null, false, false, true));
    try std.testing.expectEqualStrings("passphrase", try resolveBackendChoice(null, false, false, false));
}
