const std = @import("std");
const builtin = @import("builtin");

pub const config_rel_path = ".config/ugrant/config.toml";
pub const state_rel_dir = ".local/state/ugrant";
pub const db_filename = "state.db";
pub const keys_filename = "keys.json";
pub const secret_dir_mode: std.fs.File.Mode = 0o700;
pub const secret_file_mode: std.fs.File.Mode = 0o600;
pub const default_config =
    \\# ugrant configuration
    \\# Generated by `ugrant init`
    \\
    \\[storage]
    \\refresh_skew_seconds = 300
    \\lease_timeout_seconds = 30
    \\poll_interval_ms = 250
    \\max_wait_seconds = 60
    \\
;

pub const StorageConfig = struct {
    refresh_skew_seconds: i64 = 300,
    lease_timeout_seconds: i64 = 30,
    poll_interval_ms: u64 = 250,
    max_wait_seconds: i64 = 60,
};

pub const Paths = struct {
    config_path: []const u8,
    state_dir: []const u8,
    db_path: []const u8,
    keys_path: []const u8,

    pub fn deinit(self: Paths, allocator: std.mem.Allocator) void {
        allocator.free(self.config_path);
        allocator.free(self.state_dir);
        allocator.free(self.db_path);
        allocator.free(self.keys_path);
    }
};

fn getEnvVarOwned(allocator: std.mem.Allocator, name: []const u8) !?[]u8 {
    return std.process.getEnvVarOwned(allocator, name) catch |err| switch (err) {
        error.EnvironmentVariableNotFound => null,
        else => return err,
    };
}

fn resolveHomeDirFromValues(
    allocator: std.mem.Allocator,
    is_windows: bool,
    home: ?[]const u8,
    userprofile: ?[]const u8,
    homedrive: ?[]const u8,
    homepath: ?[]const u8,
) ![]u8 {
    if (home) |value| return allocator.dupe(u8, value);

    if (is_windows) {
        if (userprofile) |value| return allocator.dupe(u8, value);
        if (homedrive) |drive| {
            if (homepath) |path| return std.mem.concat(allocator, u8, &.{ drive, path });
        }
    }

    return error.MissingHome;
}

fn getHomeDir(allocator: std.mem.Allocator) ![]u8 {
    const home = try getEnvVarOwned(allocator, "HOME");
    defer if (home) |value| allocator.free(value);

    const profile = try getEnvVarOwned(allocator, "USERPROFILE");
    defer if (profile) |value| allocator.free(value);

    const drive = try getEnvVarOwned(allocator, "HOMEDRIVE");
    defer if (drive) |value| allocator.free(value);

    const path = try getEnvVarOwned(allocator, "HOMEPATH");
    defer if (path) |value| allocator.free(value);

    return resolveHomeDirFromValues(allocator, builtin.os.tag == .windows, home, profile, drive, path);
}

fn envVarExists(name: []const u8) bool {
    const raw = std.process.getEnvVarOwned(std.heap.page_allocator, name) catch |err| return switch (err) {
        error.EnvironmentVariableNotFound => false,
        else => false,
    };
    defer std.heap.page_allocator.free(raw);
    return true;
}

pub fn resolvePaths(allocator: std.mem.Allocator) !Paths {
    const home = try getHomeDir(allocator);
    defer allocator.free(home);
    return resolvePathsFromHome(allocator, home);
}

fn resolvePathsFromHome(allocator: std.mem.Allocator, home: []const u8) !Paths {
    const config_path = try std.fs.path.join(allocator, &.{ home, config_rel_path });
    const state_dir = try std.fs.path.join(allocator, &.{ home, state_rel_dir });
    const db_path = try std.fs.path.join(allocator, &.{ state_dir, db_filename });
    const keys_path = try std.fs.path.join(allocator, &.{ state_dir, keys_filename });
    return .{ .config_path = config_path, .state_dir = state_dir, .db_path = db_path, .keys_path = keys_path };
}

pub fn ensureParentDirs(paths: Paths) !void {
    try std.fs.cwd().makePath(paths.state_dir);
    if (std.fs.path.dirname(paths.config_path)) |config_dir| try std.fs.cwd().makePath(config_dir);
    try tightenSecretStatePermissions(paths);
}

pub fn ensureConfig(config_path: []const u8) !void {
    if (!(try fileExists(config_path))) {
        var file = try std.fs.createFileAbsolute(config_path, .{ .truncate = true, .mode = secret_file_mode });
        defer file.close();
        try file.writeAll(default_config);
    }
    try tightenFilePermissions(config_path);
}

pub fn requireInitialized(paths: Paths) !void {
    if (!(try fileExists(paths.keys_path)) or !(try fileExists(paths.db_path))) return error.NotInitialized;
    try tightenSecretStatePermissions(paths);
}

pub fn fileExists(path: []const u8) !bool {
    std.fs.accessAbsolute(path, .{}) catch |e| switch (e) {
        error.FileNotFound => return false,
        else => return e,
    };
    return true;
}

pub fn nowTs() i64 {
    return std.time.timestamp();
}

pub fn loadStorageConfig(allocator: std.mem.Allocator, config_path: []const u8) !StorageConfig {
    var cfg = StorageConfig{};
    const bytes = std.fs.cwd().readFileAlloc(allocator, config_path, 64 * 1024) catch |err| switch (err) {
        error.FileNotFound => return cfg,
        else => return err,
    };
    defer allocator.free(bytes);

    var in_storage = false;
    var lines = std.mem.splitScalar(u8, bytes, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \r\t");
        if (line.len == 0 or line[0] == '#') continue;
        if (line[0] == '[' and line[line.len - 1] == ']') {
            in_storage = std.mem.eql(u8, std.mem.trim(u8, line[1 .. line.len - 1], " \t"), "storage");
            continue;
        }
        if (!in_storage) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const key = std.mem.trim(u8, line[0..eq], " \t");
        const value = std.mem.trim(u8, line[eq + 1 ..], " \t");
        if (std.mem.eql(u8, key, "refresh_skew_seconds")) cfg.refresh_skew_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "lease_timeout_seconds")) cfg.lease_timeout_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "poll_interval_ms")) cfg.poll_interval_ms = try std.fmt.parseInt(u64, value, 10) else if (std.mem.eql(u8, key, "max_wait_seconds")) cfg.max_wait_seconds = try std.fmt.parseInt(i64, value, 10);
    }
    return cfg;
}

pub fn tightenSecretStatePermissions(paths: Paths) !void {
    if (builtin.os.tag == .windows) return;

    if (std.fs.path.dirname(paths.config_path)) |config_dir| try tightenDirPermissions(config_dir);
    try tightenDirPermissions(paths.state_dir);
    try tightenIfExists(paths.config_path, tightenFilePermissions);
    try tightenIfExists(paths.db_path, tightenFilePermissions);
    try tightenIfExists(paths.keys_path, tightenFilePermissions);
}

fn tightenIfExists(path: []const u8, comptime tightenFn: fn ([]const u8) anyerror!void) !void {
    if (!(try fileExists(path))) return;
    try tightenFn(path);
}

fn tightenDirPermissions(path: []const u8) !void {
    if (builtin.os.tag == .windows) return;
    var dir = try std.fs.openDirAbsolute(path, .{});
    defer dir.close();
    try dir.chmod(secret_dir_mode);
}

fn tightenFilePermissions(path: []const u8) !void {
    if (builtin.os.tag == .windows) return;
    var file = try std.fs.openFileAbsolute(path, .{});
    defer file.close();
    try file.chmod(secret_file_mode);
}

pub fn envTruthy(name: []const u8) bool {
    const raw = std.process.getEnvVarOwned(std.heap.page_allocator, name) catch |err| return switch (err) {
        error.EnvironmentVariableNotFound => false,
        else => false,
    };
    defer std.heap.page_allocator.free(raw);
    return std.mem.eql(u8, raw, "1") or std.ascii.eqlIgnoreCase(raw, "true") or std.ascii.eqlIgnoreCase(raw, "yes");
}

pub fn commandExists(allocator: std.mem.Allocator, name: []const u8) bool {
    const result = if (builtin.os.tag == .windows)
        std.process.Child.run(.{ .allocator = allocator, .argv = &.{ "where.exe", name }, .max_output_bytes = 4096 }) catch return false
    else
        std.process.Child.run(.{ .allocator = allocator, .argv = &.{ "sh", "-c", "command -v \"$1\" >/dev/null 2>&1", "sh", name }, .max_output_bytes = 4096 }) catch return false;
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);
    return switch (result.term) {
        .Exited => |code| code == 0,
        else => false,
    };
}

pub fn backendAvailable(allocator: std.mem.Allocator, backend: []const u8) bool {
    if (std.mem.eql(u8, backend, "tpm2")) {
        if (envTruthy("UGRANT_TEST_TPM2_AVAILABLE")) return true;
        return commandExists(allocator, "tpm2_create") and commandExists(allocator, "tpm2_unseal") and commandExists(allocator, "tpm2_createprimary") and commandExists(allocator, "tpm2_load");
    }
    if (std.mem.eql(u8, backend, "platform-secure-store")) {
        if (envTruthy("UGRANT_TEST_PLATFORM_STORE_AVAILABLE")) return true;
        if (builtin.os.tag == .windows) return true;
        return commandExists(allocator, "secret-tool") and envVarExists("DBUS_SESSION_BUS_ADDRESS");
    }
    if (std.mem.eql(u8, backend, "passphrase")) return true;
    if (std.mem.eql(u8, backend, "insecure-keyfile")) return true;
    return false;
}

pub fn resolvePlatformSecureStoreBackend(tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (builtin.os.tag == .linux and tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return error.WrapBackendUnavailable;
}

pub fn resolveBackendChoice(requested_backend: ?[]const u8, allow_insecure: bool, tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (requested_backend) |backend| {
        if (std.mem.eql(u8, backend, "insecure-keyfile")) {
            if (!allow_insecure) return error.InsecureBackendRequiresOptIn;
            return "insecure-keyfile";
        }
        if (std.mem.eql(u8, backend, "platform-secure-store")) return resolvePlatformSecureStoreBackend(tpm2_available, platform_store_available);
        if (std.mem.eql(u8, backend, "tpm2")) {
            if (!tpm2_available) return error.WrapBackendUnavailable;
            return "tpm2";
        }
        if (std.mem.eql(u8, backend, "passphrase")) return "passphrase";
        return error.WrapBackendUnavailable;
    }

    if (tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return "passphrase";
}

pub fn chooseInitBackend(allocator: std.mem.Allocator, requested_backend: ?[]const u8, allow_insecure: bool) ![]const u8 {
    return resolveBackendChoice(requested_backend, allow_insecure, backendAvailable(allocator, "tpm2"), backendAvailable(allocator, "platform-secure-store"));
}

test "choose init backend respects explicit backend and insecure opt-in" {
    const backend = try chooseInitBackend(std.testing.allocator, "passphrase", false);
    try std.testing.expectEqualStrings("passphrase", backend);
    try std.testing.expectError(error.InsecureBackendRequiresOptIn, chooseInitBackend(std.testing.allocator, "insecure-keyfile", false));
}

test "platform-secure-store resolves to strongest Linux backend" {
    if (builtin.os.tag != .linux) return;

    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice("platform-secure-store", false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice("platform-secure-store", false, false, true));
    try std.testing.expectError(error.WrapBackendUnavailable, resolveBackendChoice("platform-secure-store", false, false, false));
}

test "platform secure store is always available on windows" {
    if (builtin.os.tag != .windows) return;

    try std.testing.expect(backendAvailable(std.testing.allocator, "platform-secure-store"));
    try std.testing.expectEqualStrings("platform-secure-store", try chooseInitBackend(std.testing.allocator, null, false));
}

test "default backend selection still prefers strongest available backend" {
    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice(null, false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice(null, false, false, true));
    try std.testing.expectEqualStrings("passphrase", try resolveBackendChoice(null, false, false, false));
}

test "windows home dir resolution prefers USERPROFILE over HOMEDRIVE and HOMEPATH" {
    if (builtin.os.tag != .windows) return;

    const allocator = std.testing.allocator;

    const from_profile = try resolveHomeDirFromValues(
        allocator,
        true,
        null,
        "C:\\Users\\Aidan",
        "D:",
        "\\Users\\Fallback",
    );
    defer allocator.free(from_profile);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan", from_profile);

    const from_drive_path = try resolveHomeDirFromValues(
        allocator,
        true,
        null,
        null,
        "D:",
        "\\Users\\Fallback",
    );
    defer allocator.free(from_drive_path);
    try std.testing.expectEqualStrings("D:\\Users\\Fallback", from_drive_path);

    try std.testing.expectError(error.MissingHome, resolveHomeDirFromValues(allocator, true, null, null, "D:", null));
}

test "windows path resolution builds expected defaults from a supplied home dir" {
    if (builtin.os.tag != .windows) return;

    const paths = try resolvePathsFromHome(std.testing.allocator, "C:\\Users\\Aidan");
    defer paths.deinit(std.testing.allocator);

    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\.config\\ugrant\\config.toml", paths.config_path);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\.local\\state\\ugrant", paths.state_dir);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\.local\\state\\ugrant\\state.db", paths.db_path);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\.local\\state\\ugrant\\keys.json", paths.keys_path);
}
