const std = @import("std");
const builtin = @import("builtin");

pub const unix_config_rel_path = ".config/ugrant/config.toml";
pub const unix_state_rel_dir = ".local/state/ugrant";
pub const windows_config_rel_path = "ugrant\\config.toml";
pub const windows_state_rel_dir = "ugrant\\state";
pub const db_filename = "state.db";
pub const keys_filename = "keys.json";
pub const secret_dir_mode: std.fs.File.Mode = 0o700;
pub const secret_file_mode: std.fs.File.Mode = 0o600;
pub const default_config =
    \\# ugrant configuration
    \\# Generated by `ugrant init`
    \\
    \\[storage]
    \\refresh_skew_seconds = 300
    \\lease_timeout_seconds = 30
    \\poll_interval_ms = 250
    \\max_wait_seconds = 60
    \\
;

pub const StorageConfig = struct {
    refresh_skew_seconds: i64 = 300,
    lease_timeout_seconds: i64 = 30,
    poll_interval_ms: u64 = 250,
    max_wait_seconds: i64 = 60,
};

pub const Paths = struct {
    config_path: []const u8,
    state_dir: []const u8,
    db_path: []const u8,
    keys_path: []const u8,

    pub fn deinit(self: Paths, allocator: std.mem.Allocator) void {
        allocator.free(self.config_path);
        allocator.free(self.state_dir);
        allocator.free(self.db_path);
        allocator.free(self.keys_path);
    }
};

const WindowsBaseDirs = struct {
    config_root: []const u8,
    state_root: []const u8,

    fn deinit(self: WindowsBaseDirs, allocator: std.mem.Allocator) void {
        allocator.free(self.config_root);
        allocator.free(self.state_root);
    }
};

fn getEnvVarOwned(allocator: std.mem.Allocator, name: []const u8) !?[]u8 {
    return std.process.getEnvVarOwned(allocator, name) catch |err| switch (err) {
        error.EnvironmentVariableNotFound => null,
        else => return err,
    };
}

fn resolveHomeDirFromValues(
    allocator: std.mem.Allocator,
    is_windows: bool,
    home: ?[]const u8,
    userprofile: ?[]const u8,
    homedrive: ?[]const u8,
    homepath: ?[]const u8,
) ![]u8 {
    if (home) |value| return allocator.dupe(u8, value);

    if (is_windows) {
        if (userprofile) |value| return allocator.dupe(u8, value);
        if (homedrive) |drive| {
            if (homepath) |path| return std.mem.concat(allocator, u8, &.{ drive, path });
        }
    }

    return error.MissingHome;
}

fn getHomeDir(allocator: std.mem.Allocator) ![]u8 {
    const home = try getEnvVarOwned(allocator, "HOME");
    defer if (home) |value| allocator.free(value);

    const profile = try getEnvVarOwned(allocator, "USERPROFILE");
    defer if (profile) |value| allocator.free(value);

    const drive = try getEnvVarOwned(allocator, "HOMEDRIVE");
    defer if (drive) |value| allocator.free(value);

    const path = try getEnvVarOwned(allocator, "HOMEPATH");
    defer if (path) |value| allocator.free(value);

    return resolveHomeDirFromValues(allocator, builtin.os.tag == .windows, home, profile, drive, path);
}

fn envVarExists(name: []const u8) bool {
    const raw = std.process.getEnvVarOwned(std.heap.page_allocator, name) catch |err| return switch (err) {
        error.EnvironmentVariableNotFound => false,
        else => false,
    };
    defer std.heap.page_allocator.free(raw);
    return true;
}

pub fn resolvePaths(allocator: std.mem.Allocator) !Paths {
    const home = try getHomeDir(allocator);
    defer allocator.free(home);

    if (builtin.os.tag == .windows) {
        const appdata = try getEnvVarOwned(allocator, "APPDATA");
        defer if (appdata) |value| allocator.free(value);

        const localappdata = try getEnvVarOwned(allocator, "LOCALAPPDATA");
        defer if (localappdata) |value| allocator.free(value);

        const paths = try resolvePathsFromValues(allocator, true, home, appdata, localappdata);
        errdefer paths.deinit(allocator);

        const legacy_paths = try resolveLegacyWindowsPathsFromHome(allocator, home);
        defer legacy_paths.deinit(allocator);

        try migrateWindowsLegacyPaths(allocator, paths, legacy_paths);
        return paths;
    }

    return resolvePathsFromValues(allocator, false, home, null, null);
}

fn resolvePathsFromHome(allocator: std.mem.Allocator, home: []const u8) !Paths {
    return resolvePathsFromValues(allocator, builtin.os.tag == .windows, home, null, null);
}

fn resolvePathsFromValues(
    allocator: std.mem.Allocator,
    is_windows: bool,
    home: []const u8,
    appdata: ?[]const u8,
    localappdata: ?[]const u8,
) !Paths {
    if (is_windows) return resolveWindowsPathsFromValues(allocator, home, appdata, localappdata);

    const config_path = try std.fs.path.join(allocator, &.{ home, unix_config_rel_path });
    const state_dir = try std.fs.path.join(allocator, &.{ home, unix_state_rel_dir });
    const db_path = try std.fs.path.join(allocator, &.{ state_dir, db_filename });
    const keys_path = try std.fs.path.join(allocator, &.{ state_dir, keys_filename });
    return .{ .config_path = config_path, .state_dir = state_dir, .db_path = db_path, .keys_path = keys_path };
}

fn resolveWindowsPathsFromValues(
    allocator: std.mem.Allocator,
    home: []const u8,
    appdata: ?[]const u8,
    localappdata: ?[]const u8,
) !Paths {
    const base_dirs = try resolveWindowsBaseDirsFromValues(allocator, home, appdata, localappdata);
    defer base_dirs.deinit(allocator);

    const config_path = try joinWindowsPath(allocator, &.{ base_dirs.config_root, windows_config_rel_path });
    const state_dir = try joinWindowsPath(allocator, &.{ base_dirs.state_root, windows_state_rel_dir });
    const db_path = try joinWindowsPath(allocator, &.{ state_dir, db_filename });
    const keys_path = try joinWindowsPath(allocator, &.{ state_dir, keys_filename });
    return .{ .config_path = config_path, .state_dir = state_dir, .db_path = db_path, .keys_path = keys_path };
}

fn resolveLegacyWindowsPathsFromHome(allocator: std.mem.Allocator, home: []const u8) !Paths {
    const config_path = try std.fs.path.join(allocator, &.{ home, unix_config_rel_path });
    const state_dir = try std.fs.path.join(allocator, &.{ home, unix_state_rel_dir });
    const db_path = try std.fs.path.join(allocator, &.{ state_dir, db_filename });
    const keys_path = try std.fs.path.join(allocator, &.{ state_dir, keys_filename });
    return .{ .config_path = config_path, .state_dir = state_dir, .db_path = db_path, .keys_path = keys_path };
}

fn resolveWindowsBaseDirsFromValues(
    allocator: std.mem.Allocator,
    home: []const u8,
    appdata: ?[]const u8,
    localappdata: ?[]const u8,
) !WindowsBaseDirs {
    const config_root = if (appdata) |value|
        try allocator.dupe(u8, value)
    else
        try joinWindowsPath(allocator, &.{ home, "AppData", "Roaming" });
    errdefer allocator.free(config_root);

    const state_root = if (localappdata) |value|
        try allocator.dupe(u8, value)
    else
        try joinWindowsPath(allocator, &.{ home, "AppData", "Local" });

    return .{ .config_root = config_root, .state_root = state_root };
}

fn migrateWindowsLegacyPaths(allocator: std.mem.Allocator, current: Paths, legacy: Paths) !void {
    try migratePathIfMissing(legacy.config_path, current.config_path);
    try migrateStateDirIfNeeded(allocator, legacy, current);
}

fn migrateStateDirIfNeeded(allocator: std.mem.Allocator, legacy: Paths, current: Paths) !void {
    if (!std.mem.eql(u8, legacy.state_dir, current.state_dir)) {
        const legacy_exists = try fileExists(legacy.state_dir);
        const current_exists = try fileExists(current.state_dir);
        if (legacy_exists and !current_exists) {
            if (std.fs.path.dirname(current.state_dir)) |parent| try makePathCompat(parent);
            try std.fs.renameAbsolute(legacy.state_dir, current.state_dir);
            return;
        }
    }

    try migratePathIfMissing(legacy.db_path, current.db_path);
    try migratePathIfMissing(legacy.keys_path, current.keys_path);
    try migrateDbSidecarsIfMissing(allocator, legacy.db_path, current.db_path);
}

fn migrateDbSidecarsIfMissing(allocator: std.mem.Allocator, legacy_db_path: []const u8, current_db_path: []const u8) !void {
    inline for ([_][]const u8{ "-wal", "-shm", "-journal" }) |suffix| {
        const legacy_sidecar = try std.fmt.allocPrint(allocator, "{s}{s}", .{ legacy_db_path, suffix });
        defer allocator.free(legacy_sidecar);
        const current_sidecar = try std.fmt.allocPrint(allocator, "{s}{s}", .{ current_db_path, suffix });
        defer allocator.free(current_sidecar);
        try migratePathIfMissing(legacy_sidecar, current_sidecar);
    }
}

fn migratePathIfMissing(legacy_path: []const u8, current_path: []const u8) !void {
    if (std.mem.eql(u8, legacy_path, current_path)) return;
    if (try fileExists(current_path)) return;
    if (!(try fileExists(legacy_path))) return;

    if (std.fs.path.dirname(current_path)) |parent| try makePathCompat(parent);
    try std.fs.renameAbsolute(legacy_path, current_path);
}

fn joinWindowsPath(allocator: std.mem.Allocator, parts: []const []const u8) ![]u8 {
    var out = std.ArrayList(u8).empty;
    defer out.deinit(allocator);

    var wrote_any = false;
    for (parts, 0..) |part, idx| {
        if (part.len == 0) continue;
        const trimmed = if (idx == 0) trimWindowsTrailingSeparators(part) else trimWindowsSegment(part);
        if (trimmed.len == 0) continue;

        if (!wrote_any) {
            try out.appendSlice(allocator, trimmed);
            wrote_any = true;
            continue;
        }

        if (!endsWithWindowsSeparator(out.items)) try out.append(allocator, '\\');
        try out.appendSlice(allocator, trimmed);
    }

    return out.toOwnedSlice(allocator);
}

fn trimWindowsSegment(part: []const u8) []const u8 {
    var start: usize = 0;
    var end: usize = part.len;

    while (start < end and isWindowsSeparator(part[start])) : (start += 1) {}
    while (end > start and isWindowsSeparator(part[end - 1])) : (end -= 1) {}
    return part[start..end];
}

fn trimWindowsTrailingSeparators(part: []const u8) []const u8 {
    var end: usize = part.len;
    while (end > 0 and isWindowsSeparator(part[end - 1])) : (end -= 1) {}
    return part[0..end];
}

fn endsWithWindowsSeparator(path: []const u8) bool {
    if (path.len == 0) return false;
    return isWindowsSeparator(path[path.len - 1]);
}

fn isWindowsSeparator(ch: u8) bool {
    return ch == '\\' or ch == '/';
}

pub fn ensureParentDirs(paths: Paths) !void {
    try makePathCompat(paths.state_dir);
    if (std.fs.path.dirname(paths.config_path)) |config_dir| try makePathCompat(config_dir);
    try tightenSecretStatePermissions(paths);
}

fn makePathCompat(path: []const u8) !void {
    if (path.len == 0) return;
    if (builtin.os.tag != .windows or !std.fs.path.isAbsolute(path)) {
        try std.fs.cwd().makePath(path);
        return;
    }

    if (path.len < 3 or path[1] != ':' or !isWindowsSeparator(path[2])) {
        try std.fs.cwd().makePath(path);
        return;
    }

    var current = std.ArrayList(u8){};
    defer current.deinit(std.heap.page_allocator);
    try current.appendSlice(std.heap.page_allocator, path[0..3]);

    var index: usize = 3;
    while (index < path.len) {
        while (index < path.len and isWindowsSeparator(path[index])) : (index += 1) {}
        if (index >= path.len) break;

        const start = index;
        while (index < path.len and !isWindowsSeparator(path[index])) : (index += 1) {}
        try current.appendSlice(std.heap.page_allocator, path[start..index]);
        std.fs.makeDirAbsolute(current.items) catch |err| switch (err) {
            error.PathAlreadyExists => {},
            else => return err,
        };
        if (index < path.len) try current.append(std.heap.page_allocator, '\\');
    }
}

pub fn ensureConfig(config_path: []const u8) !void {
    if (!(try fileExists(config_path))) {
        var file = try std.fs.createFileAbsolute(config_path, .{ .truncate = true, .mode = secret_file_mode });
        defer file.close();
        try file.writeAll(default_config);
    }
    try tightenFilePermissions(config_path);
}

pub fn requireInitialized(paths: Paths) !void {
    if (!(try fileExists(paths.keys_path)) or !(try fileExists(paths.db_path))) return error.NotInitialized;
    try tightenSecretStatePermissions(paths);
}

pub fn fileExists(path: []const u8) !bool {
    std.fs.accessAbsolute(path, .{}) catch |e| switch (e) {
        error.FileNotFound => return false,
        else => return e,
    };
    return true;
}

pub fn nowTs() i64 {
    return std.time.timestamp();
}

pub fn loadStorageConfig(allocator: std.mem.Allocator, config_path: []const u8) !StorageConfig {
    var cfg = StorageConfig{};
    const bytes = std.fs.cwd().readFileAlloc(allocator, config_path, 64 * 1024) catch |err| switch (err) {
        error.FileNotFound => return cfg,
        else => return err,
    };
    defer allocator.free(bytes);

    var in_storage = false;
    var lines = std.mem.splitScalar(u8, bytes, '\n');
    while (lines.next()) |raw_line| {
        const line = std.mem.trim(u8, raw_line, " \r\t");
        if (line.len == 0 or line[0] == '#') continue;
        if (line[0] == '[' and line[line.len - 1] == ']') {
            in_storage = std.mem.eql(u8, std.mem.trim(u8, line[1 .. line.len - 1], " \t"), "storage");
            continue;
        }
        if (!in_storage) continue;
        const eq = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const key = std.mem.trim(u8, line[0..eq], " \t");
        const value = std.mem.trim(u8, line[eq + 1 ..], " \t");
        if (std.mem.eql(u8, key, "refresh_skew_seconds")) cfg.refresh_skew_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "lease_timeout_seconds")) cfg.lease_timeout_seconds = try std.fmt.parseInt(i64, value, 10) else if (std.mem.eql(u8, key, "poll_interval_ms")) cfg.poll_interval_ms = try std.fmt.parseInt(u64, value, 10) else if (std.mem.eql(u8, key, "max_wait_seconds")) cfg.max_wait_seconds = try std.fmt.parseInt(i64, value, 10);
    }
    return cfg;
}

pub fn tightenSecretStatePermissions(paths: Paths) !void {
    if (builtin.os.tag == .windows) return;

    if (std.fs.path.dirname(paths.config_path)) |config_dir| try tightenDirPermissions(config_dir);
    try tightenDirPermissions(paths.state_dir);
    try tightenIfExists(paths.config_path, tightenFilePermissions);
    try tightenIfExists(paths.db_path, tightenFilePermissions);
    try tightenIfExists(paths.keys_path, tightenFilePermissions);
}

fn tightenIfExists(path: []const u8, comptime tightenFn: fn ([]const u8) anyerror!void) !void {
    if (!(try fileExists(path))) return;
    try tightenFn(path);
}

fn tightenDirPermissions(path: []const u8) !void {
    if (builtin.os.tag == .windows) return;
    try std.posix.fchmodat(std.fs.cwd().fd, path, secret_dir_mode, 0);
}

fn tightenFilePermissions(path: []const u8) !void {
    if (builtin.os.tag == .windows) return;
    try std.posix.fchmodat(std.fs.cwd().fd, path, secret_file_mode, 0);
}

pub fn envTruthy(name: []const u8) bool {
    const raw = std.process.getEnvVarOwned(std.heap.page_allocator, name) catch |err| return switch (err) {
        error.EnvironmentVariableNotFound => false,
        else => false,
    };
    defer std.heap.page_allocator.free(raw);
    return std.mem.eql(u8, raw, "1") or std.ascii.eqlIgnoreCase(raw, "true") or std.ascii.eqlIgnoreCase(raw, "yes");
}

pub fn commandExists(allocator: std.mem.Allocator, name: []const u8) bool {
    const result = if (builtin.os.tag == .windows)
        std.process.Child.run(.{ .allocator = allocator, .argv = &.{ "where.exe", name }, .max_output_bytes = 4096 }) catch return false
    else
        std.process.Child.run(.{ .allocator = allocator, .argv = &.{ "sh", "-c", "command -v \"$1\" >/dev/null 2>&1", "sh", name }, .max_output_bytes = 4096 }) catch return false;
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);
    return switch (result.term) {
        .Exited => |code| code == 0,
        else => false,
    };
}

pub fn backendAvailable(allocator: std.mem.Allocator, backend: []const u8) bool {
    if (std.mem.eql(u8, backend, "tpm2")) {
        if (envTruthy("UGRANT_TEST_TPM2_AVAILABLE")) return true;
        return commandExists(allocator, "tpm2_create") and commandExists(allocator, "tpm2_unseal") and commandExists(allocator, "tpm2_createprimary") and commandExists(allocator, "tpm2_load");
    }
    if (std.mem.eql(u8, backend, "platform-secure-store")) {
        if (envTruthy("UGRANT_TEST_PLATFORM_STORE_AVAILABLE")) return true;
        if (builtin.os.tag == .windows or builtin.os.tag == .macos) return true;
        return commandExists(allocator, "secret-tool") and envVarExists("DBUS_SESSION_BUS_ADDRESS");
    }
    if (std.mem.eql(u8, backend, "passphrase")) return true;
    if (std.mem.eql(u8, backend, "insecure-keyfile")) return true;
    return false;
}

pub fn resolvePlatformSecureStoreBackend(tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (builtin.os.tag == .linux and tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return error.WrapBackendUnavailable;
}

pub fn resolveBackendChoice(requested_backend: ?[]const u8, allow_insecure: bool, tpm2_available: bool, platform_store_available: bool) ![]const u8 {
    if (requested_backend) |backend| {
        if (std.mem.eql(u8, backend, "insecure-keyfile")) {
            if (!allow_insecure) return error.InsecureBackendRequiresOptIn;
            return "insecure-keyfile";
        }
        if (std.mem.eql(u8, backend, "platform-secure-store")) return resolvePlatformSecureStoreBackend(tpm2_available, platform_store_available);
        if (std.mem.eql(u8, backend, "tpm2")) {
            if (!tpm2_available) return error.WrapBackendUnavailable;
            return "tpm2";
        }
        if (std.mem.eql(u8, backend, "passphrase")) return "passphrase";
        return error.WrapBackendUnavailable;
    }

    if (tpm2_available) return "tpm2";
    if (platform_store_available) return "platform-secure-store";
    return "passphrase";
}

pub fn chooseInitBackend(allocator: std.mem.Allocator, requested_backend: ?[]const u8, allow_insecure: bool) ![]const u8 {
    return resolveBackendChoice(requested_backend, allow_insecure, backendAvailable(allocator, "tpm2"), backendAvailable(allocator, "platform-secure-store"));
}

test "choose init backend respects explicit backend and insecure opt-in" {
    const backend = try chooseInitBackend(std.testing.allocator, "passphrase", false);
    try std.testing.expectEqualStrings("passphrase", backend);
    try std.testing.expectError(error.InsecureBackendRequiresOptIn, chooseInitBackend(std.testing.allocator, "insecure-keyfile", false));
}

test "platform-secure-store resolves to strongest Linux backend" {
    if (builtin.os.tag != .linux) return;

    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice("platform-secure-store", false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice("platform-secure-store", false, false, true));
    try std.testing.expectError(error.WrapBackendUnavailable, resolveBackendChoice("platform-secure-store", false, false, false));
}

test "platform secure store is always available on windows" {
    if (builtin.os.tag != .windows) return;

    try std.testing.expect(backendAvailable(std.testing.allocator, "platform-secure-store"));
    try std.testing.expectEqualStrings("platform-secure-store", try chooseInitBackend(std.testing.allocator, null, false));
}

test "platform secure store is always available on macos" {
    if (builtin.os.tag != .macos) return;

    try std.testing.expect(backendAvailable(std.testing.allocator, "platform-secure-store"));
    try std.testing.expectEqualStrings("platform-secure-store", try chooseInitBackend(std.testing.allocator, null, false));
}

test "default backend selection still prefers strongest available backend" {
    try std.testing.expectEqualStrings("tpm2", try resolveBackendChoice(null, false, true, true));
    try std.testing.expectEqualStrings("platform-secure-store", try resolveBackendChoice(null, false, false, true));
    try std.testing.expectEqualStrings("passphrase", try resolveBackendChoice(null, false, false, false));
}

test "windows home dir resolution prefers USERPROFILE over HOMEDRIVE and HOMEPATH" {
    if (builtin.os.tag != .windows) return;

    const allocator = std.testing.allocator;

    const from_profile = try resolveHomeDirFromValues(
        allocator,
        true,
        null,
        "C:\\Users\\Aidan",
        "D:",
        "\\Users\\Fallback",
    );
    defer allocator.free(from_profile);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan", from_profile);

    const from_drive_path = try resolveHomeDirFromValues(
        allocator,
        true,
        null,
        null,
        "D:",
        "\\Users\\Fallback",
    );
    defer allocator.free(from_drive_path);
    try std.testing.expectEqualStrings("D:\\Users\\Fallback", from_drive_path);

    try std.testing.expectError(error.MissingHome, resolveHomeDirFromValues(allocator, true, null, null, "D:", null));
}

test "windows base dir resolution prefers AppData env vars" {
    const allocator = std.testing.allocator;
    const base_dirs = try resolveWindowsBaseDirsFromValues(
        allocator,
        "C:\\Users\\Aidan",
        "C:\\Users\\Aidan\\AppData\\Roaming",
        "C:\\Users\\Aidan\\AppData\\Local",
    );
    defer base_dirs.deinit(allocator);

    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Roaming", base_dirs.config_root);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Local", base_dirs.state_root);
}

test "windows base dir resolution falls back to home AppData paths" {
    const allocator = std.testing.allocator;
    const base_dirs = try resolveWindowsBaseDirsFromValues(allocator, "C:\\Users\\Aidan", null, null);
    defer base_dirs.deinit(allocator);

    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Roaming", base_dirs.config_root);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Local", base_dirs.state_root);
}

test "windows path resolution builds expected defaults from a supplied home dir" {
    const paths = try resolvePathsFromValues(std.testing.allocator, true, "C:\\Users\\Aidan", "C:\\Users\\Aidan\\AppData\\Roaming", "C:\\Users\\Aidan\\AppData\\Local");
    defer paths.deinit(std.testing.allocator);

    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Roaming\\ugrant\\config.toml", paths.config_path);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Local\\ugrant\\state", paths.state_dir);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Local\\ugrant\\state\\state.db", paths.db_path);
    try std.testing.expectEqualStrings("C:\\Users\\Aidan\\AppData\\Local\\ugrant\\state\\keys.json", paths.keys_path);
}

test "windows legacy path migration moves config and state when destinations are empty" {
    const allocator = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base = try tmp.dir.realpathAlloc(allocator, ".");
    defer allocator.free(base);

    const legacy_root = try std.fs.path.join(allocator, &.{ base, "legacy" });
    defer allocator.free(legacy_root);
    const current_root = try std.fs.path.join(allocator, &.{ base, "current" });
    defer allocator.free(current_root);

    const legacy = Paths{
        .config_path = try std.fs.path.join(allocator, &.{ legacy_root, ".config", "ugrant", "config.toml" }),
        .state_dir = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant" }),
        .db_path = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant", db_filename }),
        .keys_path = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant", keys_filename }),
    };
    defer legacy.deinit(allocator);

    const current = Paths{
        .config_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Roaming", "ugrant", "config.toml" }),
        .state_dir = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state" }),
        .db_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state", db_filename }),
        .keys_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state", keys_filename }),
    };
    defer current.deinit(allocator);

    if (std.fs.path.dirname(legacy.config_path)) |parent| try makePathCompat(parent);
    if (std.fs.path.dirname(legacy.db_path)) |parent| try makePathCompat(parent);

    {
        var file = try std.fs.createFileAbsolute(legacy.config_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("legacy-config");
    }
    {
        var file = try std.fs.createFileAbsolute(legacy.db_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("legacy-db");
    }
    {
        var file = try std.fs.createFileAbsolute(legacy.keys_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("legacy-keys");
    }

    try migrateWindowsLegacyPaths(allocator, current, legacy);

    try std.testing.expect(try fileExists(current.config_path));
    try std.testing.expect(try fileExists(current.db_path));
    try std.testing.expect(try fileExists(current.keys_path));
    try std.testing.expect(!(try fileExists(legacy.config_path)));
    try std.testing.expect(!(try fileExists(legacy.db_path)));
    try std.testing.expect(!(try fileExists(legacy.keys_path)));
}

test "windows legacy path migration does not clobber an existing AppData install" {
    const allocator = std.testing.allocator;
    var tmp = std.testing.tmpDir(.{});
    defer tmp.cleanup();

    const base = try tmp.dir.realpathAlloc(allocator, ".");
    defer allocator.free(base);

    const legacy_root = try std.fs.path.join(allocator, &.{ base, "legacy" });
    defer allocator.free(legacy_root);
    const current_root = try std.fs.path.join(allocator, &.{ base, "current" });
    defer allocator.free(current_root);

    const legacy = Paths{
        .config_path = try std.fs.path.join(allocator, &.{ legacy_root, ".config", "ugrant", "config.toml" }),
        .state_dir = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant" }),
        .db_path = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant", db_filename }),
        .keys_path = try std.fs.path.join(allocator, &.{ legacy_root, ".local", "state", "ugrant", keys_filename }),
    };
    defer legacy.deinit(allocator);

    const current = Paths{
        .config_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Roaming", "ugrant", "config.toml" }),
        .state_dir = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state" }),
        .db_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state", db_filename }),
        .keys_path = try std.fs.path.join(allocator, &.{ current_root, "AppData", "Local", "ugrant", "state", keys_filename }),
    };
    defer current.deinit(allocator);

    if (std.fs.path.dirname(legacy.config_path)) |parent| try makePathCompat(parent);
    if (std.fs.path.dirname(legacy.db_path)) |parent| try makePathCompat(parent);
    if (std.fs.path.dirname(current.config_path)) |parent| try makePathCompat(parent);
    if (std.fs.path.dirname(current.db_path)) |parent| try makePathCompat(parent);

    {
        var file = try std.fs.createFileAbsolute(legacy.config_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("legacy-config");
    }
    {
        var file = try std.fs.createFileAbsolute(current.config_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("current-config");
    }
    {
        var file = try std.fs.createFileAbsolute(legacy.db_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("legacy-db");
    }
    {
        var file = try std.fs.createFileAbsolute(current.db_path, .{ .truncate = true });
        defer file.close();
        try file.writeAll("current-db");
    }

    try migrateWindowsLegacyPaths(allocator, current, legacy);

    const current_config = try std.fs.cwd().readFileAlloc(allocator, current.config_path, 1024);
    defer allocator.free(current_config);
    const current_db = try std.fs.cwd().readFileAlloc(allocator, current.db_path, 1024);
    defer allocator.free(current_db);

    try std.testing.expectEqualStrings("current-config", current_config);
    try std.testing.expectEqualStrings("current-db", current_db);
    try std.testing.expect(try fileExists(legacy.config_path));
    try std.testing.expect(try fileExists(legacy.db_path));
}
